sudo: required
language: java

services:
  - docker
  
 # env:
  #  global:
#   secure: pbhat080513/travis-ci-test
#     secure: HEROKU_API_KEY
#     secure: DOCKER_USER
#     secure: DOCKER_PASS
#     secure: TEAMS_CHANNEL_URL
  
script:
  - mvn test
  - mvn clean package
  
before_install:
  - docker pull openjdk:8-jdk-alpine
  
after_success:

- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=prajwalBhat1/travis-ci-test
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $IMAGE_NAME