sudo: required
language: java

services:
  - docker
  
script:
  - mvn test
  - mvn clean package
  
before_install:
  - docker pull openjdk:8-jdk-alpine
  
after_success:

- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build  https://github.com/prajwalBhat1/travis-test.git -t pbhat080513/travis-ci-test
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push pbhat080513/travis-ci-test:latest