sudo: required
language: java

services:
  - docker
  
before_install:
  - docker pull openjdk:8-jdk-alpine
  - base64 -d my-ec2-key-pair_64 > /home/travis/build/prajwalBhat1/travis-test/deploy_key
  - eval "$(ssh-agent -s)"
  - chmod 600 /home/travis/build/prajwalBhat1/travis-test/deploy_key
  - ssh-add /home/travis/build/prajwalBhat1/travis-test/deploy_key
  - echo -e "Host ec2-13-233-206-157.ap-south-1.compute.amazonaws.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  
after_success:

- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=pbhat080513/travis-ci-test
- docker build /home/travis/build/prajwalBhat1/travis-test -t $IMAGE_NAME:latest
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $IMAGE_NAME
#- docker save $IMAGE_NAME:latest | gzip > /home/travis/build/prajwalBhat1/travis-test/latest.tar.gz
- ssh -i "deploy_key" ec2-user@ec2-13-233-206-157.ap-south-1.compute.amazonaws.com
- docker pull pbhat080513/travis-ci-test:latest
- docker run pbhat080513/travis-ci-test:latest
- exit

#before_deploy:
 # - mkdir -p dpl_cd_upload
 # - mv latest.tar.gz dpl_cd_upload/latest.tar.gz

#script:
 # - mkdir -p dpl_cd_upload
 # - mv latest.tar.gz dpl_cd_upload/latest.tar.gz