sudo: required
language: java

services:
  - docker

addons:
  ssh_known_hosts: ec2-13-235-238-13.ap-south-1.compute.amazonaws.com
  
before_install:
  - docker pull openjdk:8-jdk-alpine
  - base64 -d my-ec2-key-pair_64 > /home/travis/build/prajwalBhat1/travis-test/deploy_key
  - eval "$(ssh-agent -s)"
  - chmod 600 /home/travis/build/prajwalBhat1/travis-test/deploy_key
  - ssh-add /home/travis/build/prajwalBhat1/travis-test/deploy_key
  - echo -e "Host ec2-13-235-238-13.ap-south-1.compute.amazonaws.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  
after_success:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=pbhat080513/travis-ci-test
- docker build /home/travis/build/prajwalBhat1/travis-test -t $IMAGE_NAME:latest
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $IMAGE_NAME

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh -i "deploy_key" ec2-user@ec2-13-235-238-13.ap-south-1.compute.amazonaws.com 'docker stop travis-test || true && docker rm travis-test || true'
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ssh -i "deploy_key" ec2-user@ec2-13-235-238-13.ap-south-1.compute.amazonaws.com 'docker run --name travis-test -d pbhat080513/travis-ci-test:latest'
    on:
      branch: master