sudo: required
language: java

services:
  - docker
  
before_install:
  - docker pull openjdk:8-jdk-alpine
  
after_success:

- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=pbhat080513/travis-ci-test
- docker build /home/travis/build/prajwalBhat1/travis-test -t $IMAGE_NAME:latest
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $IMAGE_NAME
- docker save $IMAGE_NAME:latest | gzip > latest.tar.gz


before_deploy:
  - mkdir -p dpl_cd_upload
  - mv latest.tar.gz dpl_cd_upload/latest.tar.gz


deploy:
  - provider: s3
    region: ap-south-1
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    upload_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: prajwalBhat1/travis-test
    bucket: travis-bucket-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-bucket-2
    key: latest.tar.gz
    bundle_type: tar.gz
    application: travis-test-code-deploy
    deployment_group: travis-deployment-group
    on: *2

#script:
 # - mkdir -p dpl_cd_upload
 # - mv latest.tar.gz dpl_cd_upload/latest.tar.gz